language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t julundy/multi-docker -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true julundy/multi-docker npm test 

after_success:
  - docker build -t julundy/multi-client ./client
  - docker build -t julundy/multi-server ./server
  - docker build -t julundy/multi-nginx ./nginx
  - docker build -t julundy/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push julundy/multi-client
  - docker push julundy/multi-server
  - docker push julundy/multi-nginx
  - docker push julundy/multi-worker
  
deploy: 
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-894511344406
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY